### ISSUE TITLE
Feature request: Ubuntu 18.04 support for the install script

### ISSUE THREAD

**Issue by wanxewoj** [zhiverbox/armbian-build#1]
Now that armbian-build process supports Ubuntu 18.04 (bionic), it would be great if the zHIVErbox install script (install-zhiverbox.sh) would also support bionic. There are currently a few Ubuntu 16.04 (xenial) specific instructions which cause errors on bionic.

**Comment by zciendor** [comment]
Implemented and merged! Thank's a lot @wanxewoj. Please let us know your BTC address, so we can send you a share from our donations.
