### ISSUE TITLE
after_reencrypt_move_gpg_key() doesn't copy correctly

### ISSUE THREAD

**Issue by wanxewoj** [zhiverbox/armbian-build#4]
https://github.com/zhiverbox/armbian-build/blob/34246b77e521a281058f849a8dc0f38ca5d7af59/install-zHIVErbox.sh#L1613

`after_reencrypt_move_gpg_key()` doesn't reflect that `/root/.gnupg` already exists in the source image that is being customized. Hence `cp` copies `$TMP_GNUPGHOME` into `/root/.gnupg` instead of creating it, which is not the expected result.

Therefore, copying the whole `.gnupg` directory is no the right approach. Instead the zhiverbox key should be exported from `$TMP_GNUPGHOME` and imported into `$MOUNT_DEST_ROOT/root/.gnupg` to not loose the public keys which have been imported in the source image already.

**Comment by zciendor** [comment]
Seems like this issue was introduced after `install_tor_grater()` was added to the userpatches:
https://github.com/zhiverbox/armbian-userpatches/blob/ce7d6737b20777194549eb88d613ee3cf1cec4e4/overlay/build/helpers.sh#L98

Thanks for raising this!
