### ISSUE TITLE
install-zhiverbox.sh: mention default Armbian root password in the output

### ISSUE THREAD

**Issue by wanxewoj** [zhiverbox/armbian-build#6]
The installer script should mention the default Armbian root password. Or it would be even better if zHIVErbox wouldn't even ask for it to be changed on first start but just silently disable it. It's quite annoying that the user has to:
a) know/figure-out the default Armbian root password
b) change it
c) and then it's disabled anyway.

All this can be skipped, can't it?

**Comment by zciendor** [comment]
Thanks for raising this! It can indeed be skipped if we set the date the root password was last changed using the `chage` command. E.g. set the date to the current date. Then the user shouldn't be asked on first login to change the root password.
