### ISSUE TITLE
install-zhiverbox.sh: mention usage of default zhiverbox ssh key for first-time login

### ISSUE THREAD

**Issue by wanxewoj** [zhiverbox/armbian-build#7]
The installer script should mention in it's output that for first-time login to the boot system, the user's custom ssh key can't be used just yet but the `-i ~/.ssh/id_zhiverbox_boot_default` has to be specified in addition.

**Comment by zciendor** [comment]
There's probably even a way we can get rid of this completely. According to https://unix.stackexchange.com/questions/113827/how-to-extract-files-from-uimage we could extract the initramfs within `install-zhiverbox.sh` script already, replace the dropbear authentication key directly, repackage the initramfs and avoid having to call `update-initramfs` during `z_10_post_user_setup_customization.sh` at all.
