### ISSUE TITLE
ERROR in function compile_uboot [ compilation.sh:228 ]

### ISSUE THREAD

**Issue by ChiefGyk3D** [zhiverbox/armbian-build#8]
Getting this error when building on my machine.

 ===================== WARNING ======================
This board uses CONFIG_DM_I2C_COMPAT. Please remove
(possibly in a subsequent patch in your series)
before sending patches to the mailing list.
====================================================
  CFGCHK  u-boot.cfg
[ o.k. ] Building deb [ linux-u-boot-next-odroidxu4_5.75_armhf.deb ]
[ error ] ERROR in function compile_uboot [ compilation.sh:228 ]
[ error ] Building u-boot package failed 
[ o.k. ] Process terminated

**Comment by ChiefGyk3D** [comment]
I tried it on a brand spanking new install of Ubuntu 18.04 instead of my Pop!_OS devices since it failed on my work desktop and my laptop. It's failing even on a base Ubuntu setup. So unless I am doing something wrong, there is something wrong when it is trying to compile the kernel. This time it's complaining about compilation.sh:502 on a brand new Ubuntu build

**Comment by ChiefGyk3D** [comment]
Confirmed the same compilation.sh:502 on a brand new Ubuntu 18.04 install on a spare PC using the minimal ISO and Lubuntu desktop.

**Comment by zciendor** [comment]
Thanks for your report! Could you share the information on your build steps please? 
Did you follow the build instructions from here:
https://github.com/zhiverbox/armbian-userpatches/blob/master/BUILD.md

**Comment by zciendor** [comment]
Closing due to no response.

PS: The `zhiverbox` branch was updated/merged to the current upstream master branch. Please check if this fixes your compile issues.
